### ISSUE TITLE
As-Patterns

### ISSUE THREAD

**Issue by ChrisPenner** [ennocramer/floskell#15]
Hey again! Just figured I'd drop this here; looks like floskell doesn't know about `as-patterns` yet :D

E.g. the following:

```
myfunc xs@(x:_) = undefined
```

gets formatted into:

```
myfunc xs @ (x : _) = undefined
```

Which is invalid haskell :) and will cause Floskell to fail if I run the formatter again.

Just another one for the ever growing list of feature requests. Thanks again for the tool! It's still the best one out there that I've found and is pretty dang fast!

Cheers!

**Comment by ennocramer** [comment]
Right now, as-patterns can require specifically configuring the `@` operator.  See the output of `floskell -s cramer --print-config`.

I'm unsure whether to hard-code as-patterns, as the no-space rule seems to depend on whether `TypeApplications` is active. But then again, I haven't seen any style with spaces around the `@`, so it might make sense to not treat it as an operator.

**Comment by ChrisPenner** [comment]
Makes sense! This did the trick:

```
            "@ in pattern": {
                "force-linebreak": false,
                "spaces": "none",
                "linebreaks": "after"
            },
```

As far as whether to hard code I'm not sure; but having a config option that actually breaks code if it's misconfigured isn't necessarily great 😄

**Comment by domenkozar** [comment]
Would be great to have the trick as default, as it broke our codebase :)

**Comment by ennocramer** [comment]
This is now part of the defaults, as of `floskell-0.10.4`.
