### ISSUE TITLE
Blank lines?

### ISSUE THREAD

**Issue by Rhywun** [ennocramer/floskell#19]
(1) Is there any way to eliminate the blank lines that are inserted between definitions in a `where` clause? I want to eliminate the blank line shown below.

```
 where
  output = replaceAll input configs

  total  = countAll input configs
```

(2) Is there any way to preserve a blank line between a comment and a function definition? After reformatting, the second blank line below is removed.

```
function1 = undefined

--

function2 = undefined
```

I tried the `preserve-vertical-space` option but it doesn't seem to apply in either of these instances.

Thanks!

**Comment by ennocramer** [comment]
There is sadly no option for either at the moment.  I've been thinking about compact `where` bindings before, but I could not come up with a useful set of rules, yet.  Maybe it will have to be a global on/off switch.

As for blank lines before/after comments, I think it should be possible improve the situation.

**Comment by Rhywun** [comment]
The first one is really vexing me :) - thanks @ennocramer and @amesgen for looking into this!

**Comment by ennocramer** [comment]
The first issue is resolved in `master`. Closing this issue in favor of followup issue #28.
