### ISSUE TITLE
Separate 'do' rule in layout?

### ISSUE THREAD

**Issue by ChrisPenner** [ennocramer/floskell#23]
Hi again!

I'm wondering if would be possible to add a special-case in the config for the 'do-notation' layout.
As it is, the position of `do` statements (in a declaration)  is dictated by `layout.declaration`. However; I think `do` syntax is common enough to give a special case; particularly I much prefer the `try-oneline` approach for declaration layouts; it makes much nicer use of horizontal space, however `try-oneline` will consistently wrap the `do` down to the next line, which indents the rest of the function needlessly.

e.g. `layout.declaration = flex` does this:

```haskell
myFunc1 = do
    print "hello"
    print "world"

myFunc2 anArgument = maybe (doSomething onFailure) (doSomething otherWise)
    >>= doOtherThing
```

And `layout.declaration = try-oneline` does this:

```haskell
myFunc1 =
    do
        print "hello"
        print "world"

myFunc2 anArgument =
    maybe (doSomething onFailure) (doSomething otherWise) >>= doOtherThing
```

I much prefer the `do-notation` version of `flex`; but I much prefer the less-awkward splitting of `myFunc2` of `try-oneline`.

Would it be possible to separate out the behaviour of `do` (and maybe lambda? e.g. `\a ->`) from other `declaration` layouts?

Cheers!

**Comment by robertjlooby** [comment]
I think I just ran in to this as well. I've been trying to get Johan Tibell style data declarations but with `do`s like the flex example above. Ex:

```haskell
data Enum
    = CaseA
    | CaseB
    | CaseC
    deriving (Eq,Enum,Show)

hello :: MonadIO m => m ()
hello = do
  name <- liftIO getLine
  liftIO . putStrLn $ greetings name
  where
    greetings n = "Hello " ++ n ++ "!"
```

but haven't been able to get it to work.

**Comment by ennocramer** [comment]
`master` now implements a new option, called `flexible-oneline`, which allows `do`, `mdo`, `case ... of`, `\case`, and `\... ->` to appear in `try-oneline` layouts.  For `case` and `lambda`, the case expression and the patterns must still fit on one line. I have also updated the `johan-tibell` style to use this option.

**Comment by ChrisPenner** [comment]
Fantastic, this works great! Once again thanks for super fast response and for the awesome tool!
