### ISSUE TITLE
Record field indentation

### ISSUE THREAD

**Issue by jonathanlking** [ennocramer/floskell#24]
I would like to be able style records so that the opening `{` is below the `=`. I find this useful as the length of the record name doesn't effect the indentation. e.g.

```
data Point 
  = Point 
  { pointX :: Float
  , pointY :: Float
  , pointLabel :: String
  } deriving ( Eq, Show )
 ```
I've played around with the configurations a bit, but can't seem to get this behaviour. (None of the built in styles seem to have this either). Do you know if this is possible? Thanks :smile:

**Comment by ennocramer** [comment]
Coincidentally, I was looking into just that while working on another style today. You should be able to get the desired behavior with the current `master`.

**Comment by ChrisPenner** [comment]
Cool stuff; which configuration flags trigger this behaviour now?

Also it would be nice to have json files for all the default styles referenced somewhere; it helps with cross-referencing flags when mixing/matching configs. Right now I look up the haskell source and do my best to translate 😄

**Comment by ennocramer** [comment]
You can run `floskell --style johan-tibell --print-config` to get the `json` configuration for the `johan-tibell` style, which has this behaviour.  The relevant options are `formatting/op/record`, `formatting/group/{` and `layout/record`.
