### ISSUE TITLE
Strange behavior of comments above typeclass instances

### ISSUE THREAD

**Issue by epeery** [ennocramer/floskell#34]
Comments above typeclass instances indent each time the file is formatted.

[![asciicast](https://asciinema.org/a/247997.svg)](https://asciinema.org/a/247997)

I've confirmed that this happens with other files as well.

**Comment by ennocramer** [comment]
Thank your for the report.

That is definitely a bug and I can reproduce here. I'm looking into it.

My minimal test case:

``` haskell
module Main where

-- comment
instance Foo Bar where
  foo = undefined

bar = undefined
```

**Comment by ennocramer** [comment]
Fixed in `master` and uploaded to Hackage.
