### ISSUE TITLE
Strange behavior of case statement aligning

### ISSUE THREAD

**Issue by epeery** [ennocramer/floskell#37]
Case statement aligning occasionally stops working when used with certain datatypes.
Config is the base config with case alignment turned on.

Here's a video showing some of the different senarios I found.
[![asciicast](https://asciinema.org/a/255295.svg)](https://asciinema.org/a/255295)

**Comment by ennocramer** [comment]
This is intended behavior. The idea being that if the branches have wildly different length, you probably do not want to align them. You can configure the limits to which alignment is allowed with the `formatting.align.limits` element in your `floskell.json`. See the [section on tabstop alignment](https://github.com/ennocramer/floskell/blob/master/CONFIGURATION.md#tabstop-alignment) in the documentation.

You can force Floskell to always align by setting the second value (relative limit) to `100`.
