### ISSUE TITLE
Is GHC 8.8 support planed, or is it dead?

### ISSUE THREAD

**Issue by Avi-D-coder** [ennocramer/floskell#38]

**Comment by ennocramer** [comment]
I had some trouble finding a build-plan with `Cabal-2.2.0` and `Cabal-2.4.0`, due to an indirect dependency `comonad`. `Cabal-3.0.0` seems to work, though.

I release `floskell-0.10.2` with support for `haskell-src-exts-1.22.0` and `GHC-8.8.1`.
