### ISSUE TITLE
Upload to Hackage

### ISSUE THREAD

**Issue by lukel97** [ennocramer/floskell#6]
Are there any plans to upload this to Hackage? I ask since I would be interested in trying to plug this into [haskell-ide-engine](https://github.com/haskell/haskell-ide-engine) 😃

**Comment by ennocramer** [comment]
Yes, I will upload Floskell to Hackage.  Actually, I thought I had already done so, but apparently not.  Version 0.9.0 should be up now, but there will be a few API changes in the coming weeks before I'll release a 1.0.0.

**Comment by lukel97** [comment]
Thanks! Will get it into https://github.com/haskell/haskell-ide-engine/pull/1080 soon

**Comment by lukel97** [comment]
@ennocramer  Will there be a 0.10 release before 1.0? We've had to fall back to using a submodule in HIE, it would be nice to get the new stuff via Hackage

**Comment by ennocramer** [comment]
@bubba Thanks for the reminder. I had been preparing a `0.10.0` release but got distracted by real life.  It's up now.  Cheers!
