### ISSUE TITLE
Cannot compile with GHC 9.0

### ISSUE THREAD

**Issue by wrengr** [ennocramer/floskell#66]
This library's version constraint on `base` means it cannot be compiled with ghc 9.0.1; which in turn blocks compiling [hls](https://hackage.haskell.org/package/haskell-language-server), even though both hls and [hls-floskell-plugin](https://hackage.haskell.org/package/hls-floskell-plugin) have lenient enough bounds on `base`.

**Comment by jneira** [comment]
It seems https://github.com/ennocramer/floskell/commit/1bf6cf30ef8491930e790bfa448bf05a95cdaa49 closed this?

**Comment by wrengr** [comment]
Yep, looks like that fixed it. However, the version on Hackage still doesn't have that commit.

**Comment by wrengr** [comment]
See also https://github.com/ennocramer/floskell/pull/70 (for GHC 9.2)

**Comment by jneira** [comment]
you are right, it needs a hackage release, like the aeson 2.0 compat just merged

**Comment by ennocramer** [comment]
Thank you both for your PRs. I've uploaded version 0.10.6 to Hackage, which should solve this for GHC-9.0.1 and GHC-9.2.1.
