### ISSUE TITLE
Significant runtime blowup when formatting pattern guards

### ISSUE THREAD

**Issue by Philonous** [ennocramer/floskell#67]
Floskell takes 6s on my machine to reformat the following code fragment:

```haskell
foo x | Just x1 <- Just x
      , Just x2 <- Just x1
      , Just x3 <- Just x2
      , Just x4 <- Just x3
      , Just x5 <- Just x4
      , Just x6 <- Just x5
      , Just x7 <- Just x6
      = True
```

* On my production code it takes up to 4 minutes for 20 lines. 
* Removing one of the pattern guards makes it complete instantly
* Removing floskell.json and using the implicit or an empty configuration makes it complete instantly
* The smallest floskell.json I can reproduce this with is `{ "style": "cramer" }`; I have not tried to find the individual option from the style that causes this
* I'm running floskell 0.10.5

**Comment by ennocramer** [comment]
This problem has been addressed with `floskell-0.11.0`.
