### ISSUE TITLE
inaccurate version bounds in floskell-0.9.0

### ISSUE THREAD

**Issue by hvr** [ennocramer/floskell#8]
As can be seen at 

https://hackage.haskell.org/package/floskell-0.9.0/dependencies

virtually all version bounds have been ommitted and the effect of this can be seen at

https://matrix.hackage.haskell.org/package/floskell@1549744156

where the solver had no luck finding any sound build-plan.

In order to fix this it'll be necessary to reconstruct the appropriate bounds and retroactively inject them into the `floskell-0.9.0` release via a [Hackage metadata revision](https://github.com/haskell-infra/hackage-trustees/blob/master/revisions-information.md) as this can **not** be resolved by (only) uploading a new release of `floskell` as cabal's constraint solver will still be allowed to backtrack to any of the previous releases with missing/inaccurate bounds. You can do this yourself via

https://hackage.haskell.org/package/floskell-0.9.0/floskell.cabal/edit

or, in my function as Hackage Trustee, can assist you and do it for you.

Going forward, we need your help! Please help us ensure a good user experience for users of Hackage/Cabal by the use of the [PVP](http://pvp.haskell.org/faq) mandated lower&upper bounds in order to reduce the penalty on the Hackage infrastructure as well as to avoid unnecessary extra work for you as well as for us Hackage Trustees!

The use of CI testing (such as https://github.com/haskell-CI/haskell-ci) can greatly help identify & prevent such incidents before they enter the primary Hackage index. Let me know if you need any assistance with CI or have any questions related to it.

**Comment by ennocramer** [comment]
Thank you for your report!

I have added version bounds for all dependencies and issued an update to the cabal file.

**Comment by hvr** [comment]
@ennocramer awesome, https://matrix.hackage.haskell.org/package/floskell looks much better now! :-)

PS: I'll manually upload Haddocks for you to https://hackage.haskell.org/package/floskell (now that cabal is able to compute a working build-plan) asap, as our doc-builder currently can't be restarted easily once it failed permantly for a given release

**Comment by ennocramer** [comment]
Awesome, thanks a lot!
